version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - employee-data:/app/data
    env_file:
      - .env.docker
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    env_file:
      - .env.docker
    command: tunnel run
    depends_on:
      - web

volumes:
  employee-data:
