version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - employee-data:/app/data
    environment:
      - SECRET_KEY=your_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - EMPLOYEE_CODE_PREFIX=EMP
      - EMPLOYEE_CODE_DIGITS=6

volumes:
  employee-data: