version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./employee_management.db
      - SECRET_KEY=in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - EMPLOYEE_CODE_PREFIX=EMP
      - EMPLOYEE_CODE_DIGITS=6