version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - employee-data:/app/data
    environment:
      - SECRET_KEY=your_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - EMPLOYEE_CODE_PREFIX=EMP
      - EMPLOYEE_CODE_DIGITS=6
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOTZjNjUxYmJjN2FlOWYzNDNhZGJhNGM0ZDNmOTY5MzAiLCJ0IjoiNTMxNTk0OGMtYTQyYy00NWNhLTgyNDEtMDc5YjFiMjU0OTI2IiwicyI6Ik0yWXhNbVl3T0dFdE1XUTBaaTAwTURJekxUaGtZV0l0WlRJM1pUWXlZek00TW1ZeCJ9
    command: tunnel run
    depends_on:
      - web

volumes:
  employee-data: